on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      node-version:
        type: number
        required: true

jobs:
  install:
    name: "${{ inputs.os }} / Node v${{ inputs.node-version }}"
    runs-on: ${{inputs.os}}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - id: cached-dependencies
      uses: actions/cache@v2
      with:
        path: ~/node_modules/
        key: node_modules-${{ inputs.os }}-${{ inputs.node-version }}-${{ hashFiles('**/package-lock.json') }}
    - id: install-dependencies
      if: steps.cached-dependencies.outputs.cache-hit != 'true'
      run: npm ci