on:
  workflow_call:
      inputs:
      os:
        type: string
        required: true
      node-version:
        type: number
        required: true

jobs:
  lint:
    name: "${{ inputs.os }} - node v${{ inputs.node-version }}"
    runs-on: ${{inputs.os}}

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: ~/node_modules/
        key: node_modules-${{ inputs.os }}-${{ inputs.node-version }}-${{ hashFiles('**/package-lock.json') }}

    - if: steps.cached-dependencies.outputs.cache-hit != 'true'
      run: npm ci

    - run: npm run lint