on:
  push:
    branches:
      - feature/ci-rework

jobs:

  check-ubuntu-latest-node-18:
    uses: ./.github/workflows/quality-assurance.yml
    with:
      os: ubuntu-latest
      node-version: 18

  check-ubuntu-latest-node-17:
    uses: ./.github/workflows/quality-assurance.yml
    with:
      os: ubuntu-latest
      node-version: 17

  check-ubuntu-latest-node-16:
    uses: ./.github/workflows/quality-assurance.yml
    with:
      os: ubuntu-latest
      node-version: 16

  check-windows-latest-node-18:
    uses: ./.github/workflows/quality-assurance.yml
    with:
      os: windows-latest
      node-version: 18

  check-windows-latest-node-17:
    uses: ./.github/workflows/quality-assurance.yml
    with:
      os: windows-latest
      node-version: 17

  check-windows-latest-node-16:
    uses: ./.github/workflows/quality-assurance.yml
    with:
      os: windows-latest
      node-version: 16

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      os: ubuntu-latest
      node-version: 18

  check-license:
    uses: ./.github/workflows/check-license.yml
    with:
      os: ubuntu-latest
      node-version: 18