name: test

on:
  push:
    branches:
      - feature/ci-rework

jobs:
  quality-assurance:
    uses: ./.github/workflows/quality-assurance.yml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [16, 17, 18]
    with:
      os: ${{ matrix.os }}
      node-version: ${{ matrix.node-version }}