name: test

on:
  push:
    branches:
      - feature/ci-rework

env:
  OS: ubuntu-latest
  NODE_VERSION: 18

jobs:

  build:
    uses: ./.github/workflows/step-install-dependencies.yml
    with:
      os: ${{env.OS}}
      node-version: ${{env.NODE_VERSION}}

  check-license:
    uses: ${{GITHUB_REPOSITORY}}/.github/workflows/step-install-dependencies.yml@${{GITHUB_REF_NAME}}
    with:
      os: ${{env.OS}}
      node-version: ${{env.NODE_VERSION}}
