name: test

on:
  push:
    branches:
      - feature/ci-rework

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "./.github/workflows/build.yml"
      with:
        os: "ubuntu-latest"
        node-verison: 18
