name: test

on:
  push:
    branches:
      - feature/ci-rework

jobs:

  build:
    uses: ./.github/workflows/build.yml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [16, 17, 18]
    with:
      os: ${{ matrix.os }}
      node-version: ${{ matrix.node-version }}

  test:
    uses: ./.github/workflows/test.yml
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [16, 17, 18]
    with:
      os: ${{ matrix.os }}
      node-version: ${{ matrix.node-version }}

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      os: ubuntu-latest
      node-version: 18

  check-license:
    uses: ./.github/workflows/check-license.yml
    with:
      os: ubuntu-latest
      node-version: 18
