name: test

on:
  push:
    branches:
      - feature/ci-rework

jobs:

  test:
    uses: ./.github/workflows/step-test.yml
    with:
      os: ubuntu-latest
      node-version: 18

  check-license:
    uses: ./.github/workflows/check-license.yml
    with:
      os: ubuntu-latest
      node-version: 18
