name: test

on:
  push:
    branches:
      - feature/ci-rework

jobs:

  build:
    uses: ./.github/workflows/step-install-dependencies.yml
    with:
      os: ubuntu-latest
      node-version: 18

  check-license:
    uses: ./.github/workflows/step-install-dependencies.yml
    with:
      os: ubuntu-latest
      node-version: 18
