name: test

on:
  push:
    branches:
      - feature/ci-rework

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest
      node-version: 18
  test:
    uses: ./.github/workflows/build.yml
    needs: build
    with:
      os: ubuntu-latest
      node-version: 18