name: Check license

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      node-version:
        type: number
        required: true

jobs:
  setup:
    runs-on: ${{inputs.os}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

  install-dependencies:
    needs: setup
    steps:
      uses: ./.github/workflows/step-install-dependencies.yml
      with:
        os: ${{inputs.os}}
        node-version: ${{inputs.node-version}}

  check-license:
    runs-on: ${{inputs.os}}
    needs: install-dependencies
    steps:
    - name: Run 'npm run license'
      run: npm run license
